### ISSUE TITLE
problem with CWB

### ISSUE THREAD

**Issue by JessJ-UEA** [GeoNet/GeoNetCWBQuery#8]
CWB seems to have stopped working for me (I have used it a lot in the past and as recently as last month). 

Whatever request I run, I keep getting the same error:
Using default logging configuration.
null
No matching data for [all requests], on cwb.geonet.org.nz:2061

I have tried all of the examples on the geonet page.

When I try the -lsc option, it returns:
Using default logging configuration.
line='-b' '2016/08/25 12:33:33.384' '-d' '300.0' '-lsc'
:
java.net.SocketException: Connection reset list channels
null

Could this be a problem with my institute firewall? Or is there an update I should be using?

Cheers,

**Comment by gclitheroe** [comment]
It looks like the CWB server is having issues.  I've raised and issue here https://github.com/GeoNet/help/issues/12

Hopefully it we be resolved in the next few hours.
